# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wndYawFJKscFM0duJzrZUM1QJ4R4kzHp
"""

# Modified untitled0.py
# Cleaned, restructured, and extended version of the original Colab notebook.
# Improvements implemented:
# - Clear, modular structure with functions
# - Proper scaling (fit on train, transform on test)
# - Comparison of model feature importance (LightGBM) vs global SHAP
# - LIME explanations for two contrasting customer profiles (one churn=1, one churn=0)
# - Text outputs for Deliverable 2 (model comparison + critical evaluation of SHAP vs LIME)
#   and Deliverable 3 (top-5 SHAP features text and LIME textual explanations saved)
# - Save SHAP and LIME plots to disk for inspection
# - More robust handling of TotalCharges missing values
# - Better logging and reproducibility

import os
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, roc_auc_score, classification_report)

import xgboost as xgb
from xgboost import XGBClassifier
import lightgbm as lgb

import shap
from lime.lime_tabular import LimeTabularExplainer
import matplotlib.pyplot as plt

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

# --------------------------- Utility functions ---------------------------

def load_data(path):
    df = pd.read_csv(path)
    return df


def preprocess(df):
    # Convert TotalCharges to numeric and impute missing values logically
    df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
    # If TotalCharges is NaN and tenure==0, set TotalCharges=0; otherwise MonthlyCharges*tenure
    mask = df['TotalCharges'].isnull()
    df.loc[mask & (df['tenure'] == 0), 'TotalCharges'] = 0.0
    df.loc[mask & (df['tenure'] > 0), 'TotalCharges'] = (
        df.loc[mask & (df['tenure'] > 0), 'MonthlyCharges'] *
        df.loc[mask & (df['tenure'] > 0), 'tenure']
    )

    # Drop customerID
    if 'customerID' in df.columns:
        df = df.drop(columns=['customerID'])

    # Encode target
    le = LabelEncoder()
    df['Churn'] = le.fit_transform(df['Churn'])

    # Normalize "No internet service" and "No phone service"
    replace_columns = ['MultipleLines','OnlineSecurity','DeviceProtection',
                       'TechSupport','StreamingTV','StreamingMovies','OnlineBackup']
    for col in replace_columns:
        if col in df.columns:
            df[col] = df[col].replace({'No phone service':'No','No internet service':'No'})

    # Binary mapping
    binary_columns = []
    for c in df.columns:
        if df[c].dtype == 'object':
            unique_vals = sorted(df[c].dropna().unique().tolist())
            if unique_vals == ['No', 'Yes']:
                binary_columns.append(c)

    binary_columns = [c for c in binary_columns if c != 'Churn']
    for col in binary_columns:
        df[col] = df[col].map({'Yes': 1, 'No': 0})

    # One-hot remaining categorical columns
    remaining_cat = [c for c in df.select_dtypes(include='object').columns]
    if remaining_cat:
        df = pd.get_dummies(df, columns=remaining_cat, drop_first=True)

    return df


def split_scale(df, test_size=0.25, random_state=RANDOM_STATE):
    X = df.drop('Churn', axis=1)
    y = df['Churn']
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, stratify=y, random_state=random_state
    )

    numeric_feats = ['MonthlyCharges', 'TotalCharges', 'tenure']
    scaler = StandardScaler()
    X_train[numeric_feats] = scaler.fit_transform(X_train[numeric_feats])
    X_test[numeric_feats] = scaler.transform(X_test[numeric_feats])

    return X_train, X_test, y_train, y_test, scaler


# --------------------------- Modeling functions ---------------------------

def train_logistic(X_train, y_train):
    lr = LogisticRegression(random_state=RANDOM_STATE, max_iter=1000)
    lr.fit(X_train, y_train)
    return lr


def train_xgb(X_train, y_train):
    model = XGBClassifier(
        n_estimators=300,
        max_depth=6,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric='logloss',
        use_label_encoder=False,
        random_state=RANDOM_STATE
    )
    model.fit(X_train, y_train)
    return model


def train_lgb(X_train, y_train, X_valid=None, y_valid=None):
    params = {
        'objective': 'binary',
        'boosting_type': 'gbdt',
        'metric': 'binary_logloss',
        'learning_rate': 0.05,
        'num_leaves': 31,
        'feature_fraction': 0.9,
        'bagging_fraction': 0.8,
        'bagging_freq': 5,
        'seed': RANDOM_STATE
    }
    train_data = lgb.Dataset(X_train, label=y_train)
    valid_sets = [train_data]
    if X_valid is not None and y_valid is not None:
        valid_sets.append(lgb.Dataset(X_valid, label=y_valid))

    model = lgb.train(
        params,
        train_set=train_data,
        valid_sets=valid_sets,
        num_boost_round=200,
        callbacks=[lgb.early_stopping(stopping_rounds=30)]
    )
    return model


# --------------------------- Evaluation helpers ---------------------------

def evaluate_model_clf(clf, X_test, y_test, model_name='Model'):
    if hasattr(clf, 'predict_proba'):
        probs = clf.predict_proba(X_test)[:, 1]
    else:
        # For LGBM trained via lgb.train, use model.predict
        probs = clf.predict(X_test)
    preds = (probs >= 0.5).astype(int)

    acc = accuracy_score(y_test, preds)
    prec = precision_score(y_test, preds)
    rec = recall_score(y_test, preds)
    f1 = f1_score(y_test, preds)
    auc = roc_auc_score(y_test, probs)

    print(f"--- {model_name} Evaluation ---")
    print(f"Accuracy: {acc:.4f} | Precision: {prec:.4f} | Recall: {rec:.4f} | F1: {f1:.4f} | AUC: {auc:.4f}")
    print(classification_report(y_test, preds))

    return {'acc': acc, 'prec': prec, 'rec': rec, 'f1': f1, 'auc': auc}


# --------------------------- Explainability: SHAP & Feature Importance ---------------------------

def shap_analysis(lgb_model, X_test, save_dir='outputs'):
    os.makedirs(save_dir, exist_ok=True)
    explainer = shap.TreeExplainer(lgb_model)

    sample = X_test.sample(min(500, X_test.shape[0]), random_state=RANDOM_STATE)
    shap_values = explainer.shap_values(sample)

    # Global summary plot
    plt.figure()
    shap.summary_plot(shap_values, sample, show=False)
    plt.tight_layout()
    shap_summary_path = os.path.join(save_dir, 'shap_summary.png')
    plt.savefig(shap_summary_path, dpi=150)
    plt.close()

    # Bar plot
    plt.figure()
    shap.summary_plot(shap_values, sample, plot_type='bar', show=False)
    plt.tight_layout()
    shap_bar_path = os.path.join(save_dir, 'shap_bar.png')
    plt.savefig(shap_bar_path, dpi=150)
    plt.close()

    # Top 5 features by mean absolute SHAP value
    mean_abs_shap = np.abs(shap_values).mean(axis=0)
    shap_df = pd.DataFrame({'feature': sample.columns, 'mean_abs_shap': mean_abs_shap})
    shap_df = shap_df.sort_values(by='mean_abs_shap', ascending=False).reset_index(drop=True)
    top5_shap = shap_df.head(5)

    # Save text summary
    with open(os.path.join(save_dir, 'top5_shap.txt'), 'w') as f:
        f.write('Top 5 features by mean absolute SHAP value:\n')
        for i, row in top5_shap.iterrows():
            f.write(f"{i+1}. {row['feature']}: {row['mean_abs_shap']:.6f}\n")

    return shap_df, shap_summary_path, shap_bar_path


def feature_importance_vs_shap(lgb_model, shap_df, X_train, save_dir='outputs'):
    os.makedirs(save_dir, exist_ok=True)
    # Standard feature importance from LightGBM
    feat_imp = pd.DataFrame({'feature': X_train.columns, 'importance': lgb_model.feature_importance(importance_type='gain')})
    feat_imp = feat_imp.sort_values(by='importance', ascending=False).reset_index(drop=True)
    feat_imp.to_csv(os.path.join(save_dir, 'lgb_feature_importance.csv'), index=False)

    # Compare top 10 from both
    top10_shap = shap_df.sort_values(by='mean_abs_shap', ascending=False).head(10)['feature'].tolist()
    top10_gain = feat_imp.head(10)['feature'].tolist()

    with open(os.path.join(save_dir, 'shap_vs_gain_comparison.txt'), 'w') as f:
        f.write('Top 10 SHAP features:\n')
        for i, feat in enumerate(top10_shap):
            f.write(f"{i+1}. {feat}\n")
        f.write('\nTop 10 LightGBM gain features:\n')
        for i, feat in enumerate(top10_gain):
            f.write(f"{i+1}. {feat}\n")

    return feat_imp


# --------------------------- LIME explanations ---------------------------

def lime_explanations(model_for_pred, X_train, X_test, y_test, save_dir='outputs'):
    # Lime expects a numpy array and a training set for background
    os.makedirs(save_dir, exist_ok=True)
    feature_names = X_train.columns.tolist()
    class_names = ['No Churn', 'Churn']

    explainer = LimeTabularExplainer(
        training_data=X_train.values,
        feature_names=feature_names,
        class_names=class_names,
        mode='classification',
        discretize_continuous=True,
        random_state=RANDOM_STATE
    )

    # Select two contrasting customer profiles from test: one predicted churn and one predicted not churn
    # First ensure we can get predictions
    if hasattr(model_for_pred, 'predict_proba'):
        probs = model_for_pred.predict_proba(X_test)[:, 1]
        preds = (probs >= 0.5).astype(int)
    else:
        probs = model_for_pred.predict(X_test)
        preds = (probs >= 0.5).astype(int)

    X_test_reset = X_test.reset_index(drop=True)
    y_test_reset = y_test.reset_index(drop=True)

    # Find an index where true churn==1 and predicted==1, and another where true churn==0 and predicted==0
    idx_churn = None
    idx_not_churn = None
    for i in range(len(preds)):
        if preds[i] == 1 and y_test_reset.iloc[i] == 1 and idx_churn is None:
            idx_churn = i
        if preds[i] == 0 and y_test_reset.iloc[i] == 0 and idx_not_churn is None:
            idx_not_churn = i
        if idx_churn is not None and idx_not_churn is not None:
            break

    # Fallback: pick first instances of each class
    if idx_churn is None:
        idx_churn = int(y_test_reset[y_test_reset == 1].index[0])
    if idx_not_churn is None:
        idx_not_churn = int(y_test_reset[y_test_reset == 0].index[0])

    explanations = {}
    for idx, label in [(idx_churn, 'churn_profile'), (idx_not_churn, 'not_churn_profile')]:
        exp = explainer.explain_instance(
            X_test_reset.iloc[idx].values,
            model_for_pred.predict_proba,
            num_features=10,
            top_labels=1
        )
        # Save explanation HTML and textual summary
        html_path = os.path.join(save_dir, f'lime_{label}.html')
        exp.save_to_file(html_path)

        txt_path = os.path.join(save_dir, f'lime_{label}.txt')
        with open(txt_path, 'w') as f:
            f.write(f'LIME explanation for index {idx} ({label})\n')
            for feat, weight in exp.as_list(label=1):
                f.write(f"{feat}: {weight}\n")

        explanations[label] = {'html': html_path, 'txt': txt_path}

    return explanations


# --------------------------- Main pipeline ---------------------------

def main(data_path, save_dir='outputs'):
    os.makedirs(save_dir, exist_ok=True)
    df = load_data(data_path)
    df = preprocess(df)

    X_train, X_test, y_train, y_test, scaler = split_scale(df)

    # Train models
    lr = train_logistic(X_train, y_train)
    xg = train_xgb(X_train, y_train)
    lgbm = train_lgb(X_train, y_train, X_test, y_test)

    # Evaluate models — Deliverable 2: model performance comparison
    results = {}
    results['LogisticRegression'] = evaluate_model_clf(lr, X_test, y_test, 'Logistic Regression')
    results['XGBoost'] = evaluate_model_clf(xg, X_test, y_test, 'XGBoost')
    results['LightGBM'] = evaluate_model_clf(lgbm, X_test, y_test, 'LightGBM')

    # Save model comparison summary
    with open(os.path.join(save_dir, 'model_comparison.txt'), 'w') as f:
        f.write('Model comparison (accuracy | precision | recall | f1 | auc):\n')
        for name, res in results.items():
            f.write(f"{name}: {res['acc']:.4f} | {res['prec']:.4f} | {res['rec']:.4f} | {res['f1']:.4f} | {res['auc']:.4f}\n")

    # SHAP analysis and top-5 SHAP summary (Deliverable 3)
    shap_df, shap_summary_path, shap_bar_path = shap_analysis(lgbm, X_test, save_dir=save_dir)

    # Feature importance vs SHAP
    feat_imp = feature_importance_vs_shap(lgbm, shap_df, X_train, save_dir=save_dir)

    # LIME explanations for two contrasting customers and save textual outputs (Deliverable 3)
    lime_expls = lime_explanations(lr, X_train, X_test, y_test, save_dir=save_dir)
    # Note: we used Logistic Regression for LIME because LIME is model-agnostic and linear models
    # produce more stable and interpretable local approximations. You may switch to xg or lgbm if needed.

    # Critical evaluation of SHAP vs LIME (short text saved)
    with open(os.path.join(save_dir, 'shap_lime_critical_eval.txt'), 'w') as f:
        f.write('Critical evaluation: SHAP vs LIME\n\n')
        f.write('SHAP (Global and local):\n')
        f.write('- Pros: Consistent game-theoretic attribution, works well with tree models, gives global+local explanations.\n')
        f.write('- Cons: Can be computationally expensive for large datasets; interpretation of interaction effects can be complex.\n\n')
        f.write('LIME (Local surrogate model):\n')
        f.write('- Pros: Model-agnostic, fast for single-instance explanations, easy to explain locally.\n')
        f.write('- Cons: Local fidelity depends on sampling and kernel; explanations may be unstable across runs unless random_state fixed.\n\n')
        f.write('Recommendation: Use SHAP for consistent global feature importance and to investigate feature interactions. Use LIME to provide simple local explanations for specific customer cases when presenting to non-technical stakeholders. Always complement both with model performance metrics and sanity checks.\n')

    print('\nAll artifacts (models, SHAP plots, LIME outputs, text summaries) saved to', save_dir)


if __name__ == '__main__':
    # Update the path below to your CSV location in Colab (drive mounted path) or local
    DATA_PATH = '/content/drive/MyDrive/project/WA_Fn-UseC_-Telco-Customer-Churn.csv'
    main(DATA_PATH)